### PR TITLE
Fix import of PropTypes

### PR DESCRIPTION
**Pull request by sergiou87**

### CODE REVIEW

**Comment by foxt** [comment]
Doesn't work.

**Comment by sergiou87** [comment]
Thanks for your feedback. I guess it's normal in a branch that has been sitting for 2 years in a project that was abandoned 4 years ago 🤷‍♂️ 

Feel free to submit a PR that works, I'm closing this one 👍

**Comment by foxt** [comment]
Yeah, I just ended up switching to dudigital/react-native-zoomable-view. Sorry for reviving a 2 year old PR.

**Comment by foxt** [comment]
Yeah, I just ended up switching to dudigital/react-native-zoomable-view. Sorry for reviving a 2 year old PR.

**Pull request closed without merging**
