### PR TITLE
Add support for onSingleTapConfirmed

### PR DESCRIPTION
**Pull request by doochik**
I use your library to show image in <Modal/> and I want to have an action to close the modal (single tap in my case).

Corresponding PR: https://github.com/ldn0x7dc/react-native-view-transformer/pull/4

### CODE REVIEW

**Comment by asolas** [comment]
edit react-native-view-transformer

```
componentWillMount() {
    this.gestureResponder = createResponder({
     ......
     //add this code:
      onResponderSingleTapConfirmed: (evt, gestureState) => {
        //your singletap function
      },
    });
  }
```

**Comment by doochik** [comment]
yes, this code is in corresponding PR

**Comment by ikalafat** [comment]
@ldn0x7dc please, merge this!

**Comment by ldn0x7dc** [comment]
@ikalafat Thank you!

**Comment by ikalafat** [comment]
@ldn0x7dc  thanks so much!

**Comment by srinivas1729** [comment]
Hello, the latest package version from NPM (v0.0.18) does not have this change.  

@ldn0x7dc Can you consider pushing a newer version of your package?

**Pull request merged**
